import { IExercise, IWorkout } from 'backend/api/training/training.interface.ts'

export const exercises: IExercise[] = [
  {
    name: 'Ab Rollout',
    muscleGroup: 'Core',
    synonyms: [],
    imageUrl: 'common/public/images/ab-rollout.jpg',
    videoUrl: 'common/public/videos/ab-rollout.mp4',
    description: 'An exercise that targets the abdominals using a roller.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Bicycle Crunch',
    muscleGroup: 'Core',
    synonyms: [],
    imageUrl: 'common/public/images/bicycle-crunch.jpg',
    videoUrl: 'common/public/videos/bicycle-crunch.mp4',
    description: 'An exercise that targets the obliques and abdominals.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: "Captain's Chair",
    muscleGroup: 'Core',
    synonyms: [],
    imageUrl: 'common/public/images/captains-chair.jpg',
    videoUrl: 'common/public/videos/captains-chair.mp4',
    description: "An exercise that targets the lower abs using a captain's chair.",
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Crunch',
    muscleGroup: 'Core',
    synonyms: [],
    imageUrl: 'common/public/images/crunch.jpg',
    videoUrl: 'common/public/videos/crunch.mp4',
    description: 'An exercise that targets the abdominals.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Hanging Leg Raise',
    muscleGroup: 'Core',
    synonyms: [],
    imageUrl: 'common/public/images/hanging-leg-raise.jpg',
    videoUrl: 'common/public/videos/hanging-leg-raise.mp4',
    description: 'An exercise that targets the lower abs and hip flexors using a hanging bar.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Hip Thrust',
    muscleGroup: 'Core',
    synonyms: [],
    imageUrl: 'common/public/images/hip-thrust.jpg',
    videoUrl: 'common/public/videos/hip-thrust.mp4',
    description: 'An exercise that targets the glutes and hamstrings.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Kneeling Cable Crunch',
    muscleGroup: 'Core',
    synonyms: [],
    imageUrl: 'common/public/images/kneeling-cable-crunch.jpg',
    videoUrl: 'common/public/videos/kneeling-cable-crunch.mp4',
    description: 'An exercise that targets the abdominals using a cable machine.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Leg Raise',
    muscleGroup: 'Core',
    synonyms: [],
    imageUrl: 'common/public/images/leg-raise.jpg',
    videoUrl: 'common/public/videos/leg-raise.mp4',
    description: "An exercise that targets the lower abs using a captain's chair or lying leg raise station.",
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Plank',
    muscleGroup: 'Core',
    synonyms: [],
    imageUrl: 'common/public/images/plank.jpg',
    videoUrl: 'common/public/videos/plank.mp4',
    description: 'An exercise that targets the core muscles and stabilizes the spine.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Russian Twist',
    muscleGroup: 'Core',
    synonyms: [],
    imageUrl: 'common/public/images/russian-twist.jpg',
    videoUrl: 'common/public/videos/russian-twist.mp4',
    description: 'An exercise that targets the obliques using a medicine ball or dumbbell.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Sit-Up',
    muscleGroup: 'Core',
    synonyms: [],
    imageUrl: 'common/public/images/sit-up.jpg',
    videoUrl: 'common/public/videos/sit-up.mp4',
    description: 'An exercise that targets the abdominals using bodyweight.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Stability Ball Crunch',
    muscleGroup: 'Core',
    synonyms: [],
    imageUrl: 'common/public/images/stability-ball-crunch.jpg',
    videoUrl: 'common/public/videos/stability-ball-crunch.mp4',
    description: 'An exercise that targets the abdominals using a stability ball.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Superman',
    muscleGroup: 'Core',
    synonyms: [],
    imageUrl: 'common/public/images/superman.jpg',
    videoUrl: 'common/public/videos/superman.mp4',
    description: 'An exercise that targets the lower back muscles.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Toe Toucher',
    muscleGroup: 'Core',
    synonyms: [],
    imageUrl: 'common/public/images/toe-toucher.jpg',
    videoUrl: 'common/public/videos/toe-toucher.mp4',
    description: 'An exercise that targets the abdominals and hip flexors.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },

  // Arms exercises
  {
    name: 'Bicep Curl (Cable)',
    muscleGroup: 'Arms',
    synonyms: [],
    imageUrl: 'common/public/images/bicep-curl-cable.jpg',
    videoUrl: 'common/public/videos/bicep-curl-cable.mp4',
    description: 'An exercise that targets the biceps using a cable machine.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Bicep Curl (Dumbbell)',
    muscleGroup: 'Arms',
    synonyms: [],
    imageUrl: 'common/public/images/bicep-curl-dumbbell.jpg',
    videoUrl: 'common/public/videos/bicep-curl-dumbbell.mp4',
    description: 'An exercise that targets the biceps using dumbbells.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Bicep Curl (EZ Bar)',
    muscleGroup: 'Arms',
    synonyms: [],
    imageUrl: 'common/public/images/bicep-curl-ez-bar.jpg',
    videoUrl: 'common/public/videos/bicep-curl-ez-bar.mp4',
    description: 'An exercise that targets the biceps using an EZ curl bar.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Chin Up',
    muscleGroup: 'Arms',
    synonyms: [],
    imageUrl: 'common/public/images/chin-up.jpg',
    videoUrl: 'common/public/videos/chin-up.mp4',
    description: 'An exercise that targets the lats and biceps using bodyweight.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Concentration Curl',
    muscleGroup: 'Arms',
    synonyms: [],
    imageUrl: 'common/public/images/concentration-curl.jpg',
    videoUrl: 'common/public/videos/concentration-curl.mp4',
    description: 'An exercise that targets the biceps using dumbbells or a cable machine.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Dip',
    muscleGroup: 'Arms',
    synonyms: [],
    imageUrl: 'common/public/images/dip.jpg',
    videoUrl: 'common/public/videos/dip.mp4',
    description: 'An exercise that targets the triceps and chest using parallel bars.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Dip (Machine)',
    muscleGroup: 'Arms',
    synonyms: [],
    imageUrl: 'common/public/images/dip-machine.jpg',
    videoUrl: 'common/public/videos/dip-machine.mp4',
    description: 'An exercise that targets the triceps and chest using a dip machine.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Hammer Curl',
    muscleGroup: 'Arms',
    synonyms: [],
    imageUrl: 'common/public/images/hammer-curl.jpg',
    videoUrl: 'common/public/videos/hammer-curl.mp4',
    description: 'An exercise that targets the biceps and forearms using dumbbells.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Lying Tricep Extension (Dumbbell)',
    muscleGroup: 'Arms',
    synonyms: [],
    imageUrl: 'common/public/images/lying-tricep-extension-dumbbell.jpg',
    videoUrl: 'common/public/videos/lying-tricep-extension-dumbbell.mp4',
    description: 'An exercise that targets the triceps using dumbbells.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Overhead Tricep Extension',
    muscleGroup: 'Arms',
    synonyms: [],
    imageUrl: 'common/public/images/overhead-tricep-extension.jpg',
    videoUrl: 'common/public/videos/overhead-tricep-extension.mp4',
    description: 'An exercise that targets the triceps using a cable machine or dumbbells.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Preacher Curl',
    muscleGroup: 'Arms',
    synonyms: [],
    imageUrl: 'common/public/images/preacher-curl.jpg',
    videoUrl: 'common/public/videos/preacher-curl.mp4',
    description: 'An exercise that targets the biceps using a preacher curl bench and barbell.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Reverse Curl',
    muscleGroup: 'Arms',
    synonyms: [],
    imageUrl: 'common/public/images/reverse-curl.jpg',
    videoUrl: 'common/public/videos/reverse-curl.mp4',
    description: 'An exercise that targets the forearms and brachialis using a barbell or dumbbells.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Rope Tricep Pushdown',
    muscleGroup: 'Arms',
    synonyms: [],
    imageUrl: 'common/public/images/rope-tricep-pushdown.jpg',
    videoUrl: 'common/public/videos/rope-tricep-pushdown.mp4',
    description: 'An exercise that targets the triceps using a cable machine and rope attachment.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Skull Crusher',
    muscleGroup: 'Arms',
    synonyms: [],
    imageUrl: 'common/public/images/skull-crusher.jpg',
    videoUrl: 'common/public/videos/skull-crusher.mp4',
    description: 'An exercise that targets the triceps using a barbell or dumbbells.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Wrist Curl',
    muscleGroup: 'Arms',
    synonyms: [],
    imageUrl: 'common/public/images/wrist-curl.jpg',
    videoUrl: 'common/public/videos/wrist-curl.mp4',
    description: 'An exercise that targets the forearms and wrist flexors using a barbell or dumbbells.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },

  // Back exercises
  {
    name: 'Back Extension',
    muscleGroup: 'Back',
    synonyms: [],
    imageUrl: 'common/public/images/back-extension.jpg',
    videoUrl: 'common/public/videos/back-extension.mp4',
    description: 'An exercise that targets the lower back muscles.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Bent Over Barbell Row',
    muscleGroup: 'Back',
    synonyms: [],
    imageUrl: 'common/public/images/bent-over-barbell-row.jpg',
    videoUrl: 'common/public/videos/bent-over-barbell-row.mp4',
    description: 'An exercise that targets the upper back muscles and biceps using a barbell.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Bent Over Dumbbell Row',
    muscleGroup: 'Back',
    synonyms: [],
    imageUrl: 'common/public/images/bent-over-dumbbell-row.jpg',
    videoUrl: 'common/public/videos/bent-over-dumbbell-row.mp4',
    description: 'An exercise that targets the upper back muscles and biceps using dumbbells.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Chin-Up',
    muscleGroup: 'Back',
    synonyms: [],
    imageUrl: 'common/public/images/chin-up-back.jpg',
    videoUrl: 'common/public/videos/chin-up-back.mp4',
    description: 'An exercise that targets the upper back muscles and biceps using bodyweight.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Close Grip Lat Pulldown',
    muscleGroup: 'Back',
    synonyms: [],
    imageUrl: 'common/public/images/close-grip-lat-pulldown.jpg',
    videoUrl: 'common/public/videos/close-grip-lat-pulldown.mp4',
    description: 'An exercise that targets the upper back muscles and biceps using a cable machine.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Deadlift',
    muscleGroup: 'Back',
    synonyms: [],
    imageUrl: 'common/public/images/deadlift.jpg',
    videoUrl: 'common/public/videos/deadlift.mp4',
    description: 'A compound exercise that targets the lower back, glutes, and hamstrings using a barbell.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Good Morning',
    muscleGroup: 'Back',
    synonyms: [],
    imageUrl: 'common/public/images/good-morning.jpg',
    videoUrl: 'common/public/videos/good-morning.mp4',
    description: 'An exercise that targets the lower back, glutes, and hamstrings using a barbell.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Inverted Row',
    muscleGroup: 'Back',
    synonyms: [],
    imageUrl: 'common/public/images/inverted-row.jpg',
    videoUrl: 'common/public/videos/inverted-row.mp4',
    description: 'An exercise that targets the upper back muscles using a horizontal bar.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Lat Pulldown',
    muscleGroup: 'Back',
    synonyms: [],
    imageUrl: 'common/public/images/lat-pulldown.jpg',
    videoUrl: 'common/public/videos/lat-pulldown.mp4',
    description: 'An exercise that targets the upper back muscles and biceps using a cable machine.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Pull-Up',
    muscleGroup: 'Back',
    synonyms: [],
    imageUrl: 'common/public/images/pull-up.jpg',
    videoUrl: 'common/public/videos/pull-up.mp4',
    description: 'An exercise that targets the upper back muscles and biceps using bodyweight.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Seated Cable Row',
    muscleGroup: 'Back',
    synonyms: [],
    imageUrl: 'common/public/images/seated-cable-row.jpg',
    videoUrl: 'common/public/videos/seated-cable-row.mp4',
    description: 'An exercise that targets the upper back muscles and biceps using a cable machine.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'T-Bar Row',
    muscleGroup: 'Back',
    synonyms: [],
    imageUrl: 'common/public/images/t-bar-row.jpg',
    videoUrl: 'common/public/videos/t-bar-row.mp4',
    description: 'An exercise that targets the upper back muscles and biceps using a T-bar row machine.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },

  // Chest exercises
  {
    name: 'Bench Press',
    muscleGroup: 'Chest',
    synonyms: [],
    imageUrl: 'common/public/images/bench-press.jpg',
    videoUrl: 'common/public/videos/bench-press.mp4',
    description: 'A compound exercise that targets the chest using a barbell.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Cable Crossover',
    muscleGroup: 'Chest',
    synonyms: [],
    imageUrl: 'common/public/images/cable-crossover.jpg',
    videoUrl: 'common/public/videos/cable-crossover.mp4',
    description: 'An exercise that targets the chest using a cable machine.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Chest Dip',
    muscleGroup: 'Chest',
    synonyms: [],
    imageUrl: 'common/public/images/chest-dip.jpg',
    videoUrl: 'common/public/videos/chest-dip.mp4',
    description: 'An exercise that targets the lower chest and triceps using parallel bars.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Chest Fly (Dumbbell)',
    muscleGroup: 'Chest',
    synonyms: [],
    imageUrl: 'common/public/images/chest-fly-dumbbell.jpg',
    videoUrl: 'common/public/videos/chest-fly-dumbbell.mp4',
    description: 'An exercise that targets the chest using dumbbells.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Incline Bench Press',
    muscleGroup: 'Chest',
    synonyms: [],
    imageUrl: 'common/public/images/incline-bench-press.jpg',
    videoUrl: 'common/public/videos/incline-bench-press.mp4',
    description: 'A variation of the bench press that targets the upper chest using a barbell.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Decline Bench Press',
    muscleGroup: 'Chest',
    synonyms: [],
    imageUrl: 'common/public/images/decline-bench-press.jpg',
    videoUrl: 'common/public/videos/decline-bench-press.mp4',
    description: 'A variation of the bench press that targets the lower chest using a barbell.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Push-Up',
    muscleGroup: 'Chest',
    synonyms: [],
    imageUrl: 'common/public/images/push-up.jpg',
    videoUrl: 'common/public/videos/push-up.mp4',
    description: 'An exercise that targets the chest and triceps using bodyweight.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },

  // Legs exercises
  {
    name: 'Barbell Back Squat',
    muscleGroup: 'Legs',
    synonyms: [],
    imageUrl: 'common/public/images/barbell-back-squat.jpg',
    videoUrl: 'common/public/videos/barbell-back-squat.mp4',
    description: 'A compound exercise that targets the quads, hamstrings, and glutes using a barbell.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Barbell Deadlift',
    muscleGroup: 'Legs',
    synonyms: [],
    imageUrl: 'common/public/images/barbell-deadlift.jpg',
    videoUrl: 'common/public/videos/barbell-deadlift.mp4',
    description: 'A compound exercise that targets the lower back, glutes, and hamstrings using a barbell.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Box Jump',
    muscleGroup: 'Legs',
    synonyms: [],
    imageUrl: 'common/public/images/box-jump.jpg',
    videoUrl: 'common/public/videos/box-jump.mp4',
    description: 'An explosive exercise that targets the leg muscles and improves power and agility.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Bulgarian Split Squat',
    muscleGroup: 'Legs',
    synonyms: [],
    imageUrl: 'common/public/images/bulgarian-split-squat.jpg',
    videoUrl: 'common/public/videos/bulgarian-split-squat.mp4',
    description: 'An exercise that targets the quads and glutes using a split stance.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Calf Raise',
    muscleGroup: 'Legs',
    synonyms: [],
    imageUrl: 'common/public/images/calf-raise.jpg',
    videoUrl: 'common/public/videos/calf-raise.mp4',
    description: 'An exercise that targets the calf muscles using a calf raise machine or bodyweight.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Glute Bridge',
    muscleGroup: 'Legs',
    synonyms: [],
    imageUrl: 'common/public/images/glute-bridge.jpg',
    videoUrl: 'common/public/videos/glute-bridge.mp4',
    description: 'An exercise that targets the glutes and hamstrings.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Leg Press',
    muscleGroup: 'Legs',
    synonyms: [],
    imageUrl: 'common/public/images/leg-press.jpg',
    videoUrl: 'common/public/videos/leg-press.mp4',
    description: 'An exercise that targets the quads, hamstrings, and glutes using a leg press machine.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Lunge',
    muscleGroup: 'Legs',
    synonyms: [],
    imageUrl: 'common/public/images/lunge.jpg',
    videoUrl: 'common/public/videos/lunge.mp4',
    description: 'An exercise that targets the quads, hamstrings, and glutes using bodyweight or dumbbells.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Romanian Deadlift',
    muscleGroup: 'Legs',
    synonyms: [],
    imageUrl: 'common/public/images/romanian-deadlift.jpg',
    videoUrl: 'common/public/videos/romanian-deadlift.mp4',
    description: 'An exercise that targets the hamstrings and glutes using a barbell or dumbbells.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Step-Up',
    muscleGroup: 'Legs',
    synonyms: [],
    imageUrl: 'common/public/images/step-up.jpg',
    videoUrl: 'common/public/videos/step-up.mp4',
    description: 'An exercise that targets the quads, hamstrings, and glutes using a step or box.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },

  // Shoulders exercises
  {
    name: 'Arnold Press',
    muscleGroup: 'Shoulders',
    synonyms: [],
    imageUrl: 'common/public/images/arnold-press.jpg',
    videoUrl: 'common/public/videos/arnold-press.mp4',
    description: 'An exercise that targets the shoulders using dumbbells.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Barbell Overhead Press',
    muscleGroup: 'Shoulders',
    synonyms: [],
    imageUrl: 'common/public/images/barbell-overhead-press.jpg',
    videoUrl: 'common/public/videos/barbell-overhead-press.mp4',
    description: 'An exercise that targets the shoulders using a barbell.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Dumbbell Lateral Raise',
    muscleGroup: 'Shoulders',
    synonyms: [],
    imageUrl: 'common/public/images/dumbbell-lateral-raise.jpg',
    videoUrl: 'common/public/videos/dumbbell-lateral-raise.mp4',
    description: 'An exercise that targets the side delts using dumbbells.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Face Pull',
    muscleGroup: 'Shoulders',
    synonyms: [],
    imageUrl: 'common/public/images/face-pull.jpg',
    videoUrl: 'common/public/videos/face-pull.mp4',
    description: 'An exercise that targets the rear delts and upper back using a cable machine.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Front Dumbbell Raise',
    muscleGroup: 'Shoulders',
    synonyms: [],
    imageUrl: 'common/public/images/front-dumbbell-raise.jpg',
    videoUrl: 'common/public/videos/front-dumbbell-raise.mp4',
    description: 'An exercise that targets the front delts using dumbbells.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Lateral Dumbbell Raise',
    muscleGroup: 'Shoulders',
    synonyms: [],
    imageUrl: 'common/public/images/lateral-dumbbell-raise.jpg',
    videoUrl: 'common/public/videos/lateral-dumbbell-raise.mp4',
    description: 'An exercise that targets the side delts using dumbbells.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Reverse Pec Deck Fly',
    muscleGroup: 'Shoulders',
    synonyms: [],
    imageUrl: 'common/public/images/reverse-pec-deck-fly.jpg',
    videoUrl: 'common/public/videos/reverse-pec-deck-fly.mp4',
    description: 'An exercise that targets the rear delts using a pec deck machine.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Seated Dumbbell Shoulder Press',
    muscleGroup: 'Shoulders',
    synonyms: [],
    imageUrl: 'common/public/images/seated-dumbbell-shoulder-press.jpg',
    videoUrl: 'common/public/videos/seated-dumbbell-shoulder-press.mp4',
    description: 'An exercise that targets the shoulders using dumbbells while seated.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Shrug',
    muscleGroup: 'Shoulders',
    synonyms: [],
    imageUrl: 'common/public/images/shrug.jpg',
    videoUrl: 'common/public/videos/shrug.mp4',
    description: 'An exercise that targets the trapezius muscles using a barbell or dumbbells.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
  {
    name: 'Upright Row',
    muscleGroup: 'Shoulders',
    synonyms: [],
    imageUrl: 'common/public/images/upright-row.jpg',
    videoUrl: 'common/public/videos/upright-row.mp4',
    description: 'An exercise that targets the shoulders and upper traps using a barbell or dumbbells.',
    sets: [
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
      { repetitions: 10, weight: 20 },
    ],
  },
]

export const workouts: IWorkout[] = [
  {
    id: 'workout1',
    name: 'Chest',
    category: 'Category1',
    exercises: [exercises[0], exercises[1], exercises[2]],
  },
  {
    id: 'workout2',
    name: 'Back',
    category: 'Category2',
    exercises: [exercises[3], exercises[4], exercises[5]],
  },
  {
    id: 'workout3',
    name: 'Legs',
    category: 'Category3',
    exercises: [exercises[6], exercises[7], exercises[8]],
  },
]
